############################################################
#
# Chromecast Radio Control
#
############################################################

############################################################
#
# Stop Streaming Radio on Chromecast
#
############################################################

- alias: STOP Streaming Radio on CHROMECAST
  trigger:
    - platform: state
      entity_id: input_select.radio_station
      to: "None"
  action:
    service: media_player.turn_off
    data_template:
      entity_id: >
          {% if is_state("input_select.radio_player", "Living Room") %}
            media_player.living_room
          {%-elif is_state("input_select.radio_player", "Kitchen") %}
            media_player.kitchen
          {%-elif is_state("input_select.radio_player", "Bedroom") %}
            media_player.bedroom
          {%-elif is_state("input_select.radio_player", "Downstairs Media Players") %}
            media_player.kitchen_2
          {% else %}
            "None"
          {% endif %}

############################################################
#
# Start Streaming Radio on Chromecast
#
############################################################

- alias: START Streaming Radio on CHROMECAST
  trigger:
    - platform: state
      entity_id: input_select.radio_station
  action:
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state("input_select.radio_player", "Living Room") %}
            media_player.living_room
          {%-elif is_state("input_select.radio_player", "Kitchen") %}
            media_player.kitchen
          {%-elif is_state("input_select.radio_player", "Bedroom") %}
            media_player.bedroom
          {% else %}
            "None"
          {% endif %}
        media_content_id: >
          {% if is_state("input_select.radio_station", "1940s UK Radio") %}
            http://91.121.134.23:8100/stream
          {%-elif is_state("input_select.radio_station", "BBC Radio 2") %}
            http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio2_mf_p
          {%-elif is_state("input_select.radio_station", "BBC Radio 3") %}
            http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio3_mf_p
          {%-elif is_state("input_select.radio_station", "BBC Radio 4") %}
            http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4fm_mf_p 
          {%-elif is_state("input_select.radio_station", "BBC Radio 4 Extra") %}
            http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio4extra_mf_p
          {%-elif is_state("input_select.radio_station", "Classic FM") %}
            http://media-the.musicradio.com:80/ClassicFMMP3
          {%-elif is_state("input_select.radio_station", "Northsound 2") %}
            http://icy-e-bz-09-boh.sharp-stream.com:8000/northsound2.mp3
          {%-elif is_state("input_select.radio_station", "NECR") %}
            http://webradio.radiomonitor.com/stream/NECR
          {%-elif is_state("input_select.radio_station", "KCR") %}
            http://icecast.commedia.org.uk:8000/keithcommunityradio.mp3
          {% else %}
            "None"
          {% endif %}
        media_content_type: 'audio/mp4'
